### ISSUE TITLE
Progress / Roadmap

### ISSUE THREAD

**Issue by phiresky** [AnyhowStep/tsql#16]
Hey @AnyhowStep,
As a user of [@hediet/typed-sql](https://github.com/hediet/ts-typed-sql) I'm eager to try this library, especially for the sqlite support and since it looks like you are spending a lot of effort on making this well designed.

It would be great if you could show the status of features for example with an open issue per incomplete feature (e.g. sqlite query generation) people can subscribe to. I see there seems to be an sqlite query generator [in the tests directory](https://github.com/AnyhowStep/tsql/blob/master/test/sqlite-sqlfier.ts) but I guess that's not for public usage :)

**Comment by AnyhowStep** [comment]
Thanks for showing an interest in this project!

> especially for the sqlite support

May I know which kind of SQLite support?
Is it https://github.com/kripken/sql.js/ or https://github.com/mapbox/node-sqlite3 or some other project?

> there seems to be an sqlite query generator ... but I guess that's not for public usage :)

You're right. That code is basically hacked together so I can sanity check that the query builder will work with future adapter libraries (for SQLite, MySQL, PostgreSQL, etc.?)

If I cannot generate a query string from the input objects, then I know I've messed up seriously somewhere. Being able to generate a query string means I may or may not have messed up; but at least I didn't mess up too bad.

> It would be great if you could show the status of features for example with an open issue per incomplete feature (e.g. sqlite query generation) people can subscribe to.

You're right that I should be more organized with this project. Especially if I want to attract more interest! I'll try and get this done.

I have a few other things on my plate at the moment (before I work on proper adapter libraries),
+ Feature parity with an earlier prototype of this library
+ More documentation
+ 100% run-time code coverage
+ More compile-time tests
+ Other stuff I have forgotten

Github issues will definitely help with organizing the work!

**Comment by phiresky** [comment]
Thanks for your detailed response!

> May I know which kind of SQLite support?

In this case, probably [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3) (which are alternative synchronous node bindings that work very well). For a different project I might want to try (a webextension), probably a wasm version, but sql.js might not be adequate since it doesn't support storage backends other than pure in-memory.

> You're right that I should be more organized with this project. Especially if I want to attract more interest!

There's also the milestones feature in github (to track pending issues before a release is possible) but that might be overkill. On the other hand, this project seems to already be organized better than most, don't let perfect be the enemy of good. Doing more meta-level stuff also increases overhead and maybe delays you more, so do what you think is best :)

**Comment by AnyhowStep** [comment]
I just took a look at better-sqlite3.
I like how they actually bothered to have proper `int64` support, probably way before `BigInt` was a thing.

I had to hack sql.js to use the `BigInt` function for my tests.

**Comment by AnyhowStep** [comment]
Tracked here,
https://github.com/AnyhowStep/tsql/issues/21
