### ISSUE TITLE
Doc's ToC link to From Clause points to wrong page

### ISSUE THREAD

**Issue by pachoclo** [AnyhowStep/tsql#17]
Pointing to:
https://github.com/AnyhowStep/tsql/blob/master/doc/00-getting-started/01a-null-safe-equality.md

Instead of:
https://github.com/AnyhowStep/tsql/blob/master/doc/00-getting-started/02-from-clause.md

**Comment by AnyhowStep** [comment]
Thanks for spotting those mistakes!

I could have sworn I checked them all every time I pushed... I'll make sure to go over them all after work ><
