### ISSUE TITLE
Application-level database events

### ISSUE THREAD

**Issue by AnyhowStep** [AnyhowStep/tsql#54]
Stuff like,
`OnInsertAndFetch`, `OnUpdateAndFetchOne`, `OnInsertOne`, `OnInsertMany`, `OnUpdate`, `OnDelete`, `OnInsertSelect`, `OnReplace`, etc.

It should be tied to a particular `IPool`.

-----

### Rough Idea of API

```ts
myPool.addOnInsertAndFetchListener(myTable, async (eventData) => {
  //The fetched row after inserting
  eventData.row;
  //This should be `myTable`
  eventData.table;
  //The connection used to insert and fetch the row.
  //May or may not be in a transaction.
  eventData.connection;
  //This should be `myPool`
  eventData.pool;

  eventData.addOnCommitListener(() => {
    //Should fetch the inserted row successfully
    myPool
      .acquire((connection) => {
        return myTable.fetchOneByPrimaryKey(connection, eventData.row);
      })
      .then(console.log);
  });

  eventData.addOnRollbackListener(() => {
    //Should throw `RowNotFoundError`
    myPool
      .acquire((connection) => {
        return myTable.fetchOneByPrimaryKey(connection, eventData.row);
      })
      .catch(console.error);
  });

  //Be careful, may cause `eventData.connection` to rollback its transaction if an error is thrown.
  //Or may cause code using `eventData.connection` to execute partially, if an error is thrown.
  await myLog.insertOne(eventData.connection, {
    description : `A row was inserted for table ${eventData.table.alias}`,
    row : JSON.stringify(eventData.row),
  });
});
```

If `eventData.connection` is not in a transaction, `addOnCommitListener()` should invoke the callback **after** `eventData.connection` has been released. So, it should still be invoked asynchronously.

If `eventData.connection` is not in a transaction, `addOnRollbackListener()` should never invoke its callback, since there is nothing to rollback.

Alternatively, instead of waiting for commit/rollback, one can use `eventData.connection` to do other stuff, which may cause a transaction to fail

-----

[EDIT]

List of planned events,

### `INSERT`-related

+ [x] `onInsert`
  Will be called for all executed `INSERT ... VALUES`, `INSERT IGNORE ... VALUES` statements
+ [x] `onInsertOne`
  Will be called when `insertOne()`, `insertIgnoreOne()` is executed.
+ [x] `onInsertAndFetch`
  Will be called when `insertAndFetch()`, `insertIgnoreAndFetch()` is executed

-----

+ [x] `onInsertSelect`
  Will be called for all executed `INSERT ... SELECT`, `INSERT IGNORE ... SELECT` statements

-----

### `REPLACE`-related

A `REPLACE` statement may insert rows, or it may both delete and insert rows.

It is possible for a `REPLACE` statement to insert more rows than deleted.
It is possible for a `REPLACE` statement to insert fewer rows than deleted.

+ [x] `onReplace`
  Will be called for all executed `REPLACE ... VALUES` statements
+ [x] `onReplaceOne`
  Will be called when `replaceOne()` is executed.
+ [ ] `onReplaceAndFetch`
  Will be called when `replaceAndFetch()` is executed

-----

+ [x] `onReplaceSelect`
  Will be called for all executed `REPLACE ... SELECT` statements

-----

### `UPDATE`-related

+ [x] `onUpdate`
  Will be called for all executed `UPDATE` statements
+ [x] `onUpdateAndFetch`
  Will be called when `updateAndFetchXxx()` is executed

-----

### `DELETE`-related

+ [x] `onDelete`
  Will be called for all executed `DELETE` statements

**Comment by G-Rath** [comment]
Is there any particular reason to not use the standard EventEmitter class?

You could strongly type it w/ something like [`strongly-typed-event-emitter`](https://www.npmjs.com/package/strongly-typed-event-emitter), and so (hopefully) retain the same level of type enforcement.

I don't have anything against `add<OnEvent>Listener`, but I think there's value in conforming to standard js convention if it doesn't cost anything 🤷‍♂ 

-----

I'm guessing it's b/c of the `myTable` parameter, but even then, I think there could be value in going for following the standard on/off/once/etc pattern.

**Comment by AnyhowStep** [comment]
In my head, I wanted the `myTable` part because I didn't want to have the following,

```ts
myPool.on("insertAndFetch", async (eventData) => {
  if (eventData.table != myTable) {
    return;
  }
  //snip async code
});
```

But now that I'm looking at it, it may make sense for someone to want to listen to `"insertAndFetch"` events for all arbitrary tables...

The other thing is that I don't like the idea of having strings to identify which event to listen to.

I'd rather have,
```ts
myPool.addOnXListener(...);
myPool.addOnYListener(...);
```

Rather than,
```ts
myPool.on("x", ...);
myPool.on("y", ...);
```

In general, the first choice requires no generics, and no overloads. The second choice requires some kind of generics, or overloads, to map the string literals to specific event types.

**Comment by G-Rath** [comment]
> But now that I'm looking at it, it may make sense for someone to want to listen to "insertAndFetch" events for all arbitrary tables...

Go for the simple generic version first - you can always overload it later to take a table as the first parameter pretty easily 🙂 

> The other thing is that I don't like the idea of having strings to identify which event to listen to.
You can always provide enums 😉

> I'd rather have this,

To be honest, I prefer the `.on(...`, as I find it can be more readable.

In addition, you can wrap it easier:
```
myPool.addOnInsertAndFetchListener( ...

// vs

myPool.on(
  'insertAndFetch',
  (/* ... */ ) => {
    /* ... */
  }
);
```

> Should I just have query execution errors go to the "error" event? Should errors thrown from "insertAndFetch" handlers also go to this "error" event?

That can be solved by using named errors, which is going to be important to use anyway in a library such as this.

> So far, in my head, errors should just be handled by the code that is trying to execute the query, not some random event handler in an unrelated location, acting as a catch-all to log it. But there may be valid use cases for it...

I think that makes sense, but also think there is use in being able to listen for general errors & such, for things like logging & debugging.

It's best to throw as close to the original callsite as possible; it's easier to write an abstraction to bubble events up than to try and pass them down to the callsite 🙂

**Comment by AnyhowStep** [comment]
> `EventEmitter` does nothing w/ the return.

That's exactly the problem with `EventEmitter`, though. I want it to `await` any returned promises before executing the next handler.

**Comment by G-Rath** [comment]
> I want it to await any returned promises before executing the next handler.

That's exactly the problem though; that's not how event listening works - you're describing a middleware stack 😉

**Comment by AnyhowStep** [comment]
I just updated my above comment.

I usually see middleware stacks as having a well defined execution order, and also as being hard to cause handlers to cycle infinitely.

In this case, it's easy to cause an infinite loop.

1. OnInsert of tableA, insert a row to tableB
2. OnInsert of tableB, insert a row to tableA
3. Insert to tableA
4. Infinite loop

Whereas with a middleware stack, you generally just have a pipeline. Data goes into the start and keeps moving forward through the pipe, and comes out the end. (Certain middleware may be skipped and whatnot but you usually don't see cycles)

**Comment by G-Rath** [comment]
> I usually see middleware stacks as having a well defined execution order, and also as being hard to cause handlers to cycle infinitely.

Middleware, interceptor, etc - main point is it's a stack 😄 

If you do things in order, I'd advice *not* calling it a listener - that doesn't imply sequential.
Instead, I'd favor something like "register" - i.e "registerInsertAndFetchHandler`.

**Comment by AnyhowStep** [comment]
Thanks for letting me bounce ideas off you <3

**Comment by G-Rath** [comment]
No problem - always keen for a good bouncing 😉 

Besides, it gives me a chance to make semi-cryptic comments that make it seem like I actually know what I'm talking about, and who doesn't that? 😄

**Comment by G-Rath** [comment]
No problem - always keen for a good bouncing 😉 

Besides, it gives me a chance to make semi-cryptic comments that make it seem like I'm wise & actually know what I'm talking about, and who doesn't love that? 😄 

-----

But seriously no problem - feel free to @ me anytime :)
